# Generated by Django 4.2.7 on 2024-01-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorym',
        ),
    ]
