# Generated by Django 4.2.7 on 2024-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_category_categorym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[], max_length=24),
        ),
        migrations.DeleteModel(
            name='Categorym',
        ),
    ]
